Refaktor yaml, dodanie allure-report

diff --git a/.github/workflows/ci-tests.yaml b/.github/workflows/ci-tests.yaml
--- a/.github/workflows/ci-tests.yaml
+++ b/.github/workflows/ci-tests.yaml
@@ -22,9 +22,6 @@ jobs:
           python-version: "3.12"
           cache: "pip"
 
-      - name: Install Playwright system deps
-        uses: microsoft/playwright-github-action@v1
-
       - name: Install Python dependencies
         shell: pwsh
         run: |
@@ -35,16 +32,26 @@ jobs:
       - name: Run Playwright tests
         shell: pwsh
         run: |
-          pytest -vv -s --alluredir=allure-results --browser=chromium --output=test-results --screenshot=only-on-failure --video=retain-on-failure --tracing=retain-on-failure || echo "Tests failed"
-      
+          pytest -vv -s --alluredir=allure-results || echo "Tests failed"
 
-      - name: Upload Allure results
-        uses: actions/upload-artifact@v4
+      - name: List Allure results
+        shell: pwsh
+        run: |
+          if (Test-Path "allure-results") {
+            Get-ChildItem "allure-results" -Recurse | ForEach-Object { Write-Host $_.FullName }
+          } else {
+            Write-Host "Folder allure-results does not exist!"
+          }
+
+      - name: Generate Allure HTML report
         if: always()
-        with:
-          name: allure-results
-          path: allure-results
-          if-no-files-found: ignore
+        shell: pwsh
+        run: |
+          if (Test-Path "allure-results") {
+            & "$env:ALLURE_CMD" generate "allure-results" -o "allure-report" --clean
+          } else {
+            Write-Host "No allure-results folder, skipping HTML report"
+          }
 
       - name: Install Allure CLI
         shell: pwsh
